# Generated by Django 6.1 on 2026-08-09 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название раздела')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-слаг')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в меню')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок статьи')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-слаг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Фото статьи')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Или прямая ссылка на фото (URL)')),
                ('preview_text', models.TextField(max_length=300, verbose_name='Краткое описание (для плитки)')),
                ('content', models.TextField(verbose_name='Полный текст статьи')),
                ('is_featured_on_home', models.BooleanField(default=False, verbose_name='Показывать плитку на Главном экране')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='main.category', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
    ]
